// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHSG-qYiwwhwdTWxHInFV8p8f8BATc-sk',
    appId: '1:27568309259:android:cea6bb150cc697b69bf30e',
    messagingSenderId: '27568309259',
    projectId: 'dice2-1f790',
    databaseURL: 'https://dice2-1f790.firebaseio.com',
    storageBucket: 'dice2-1f790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi7QYXezXU9qqHGq87judvq2vovZkpqoY',
    appId: '1:27568309259:ios:fab2a5dc58c4c6709bf30e',
    messagingSenderId: '27568309259',
    projectId: 'dice2-1f790',
    databaseURL: 'https://dice2-1f790.firebaseio.com',
    storageBucket: 'dice2-1f790.appspot.com',
    androidClientId: '27568309259-3nak6aki2609c6759a2kv0rrel2lv2ml.apps.googleusercontent.com',
    iosClientId: '27568309259-pumm6kldd5clnu5njnvlfreu7lea89qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.yuvaAgain',
  );
}
